name: Build and Deploy
on:
  push:
    branches:
      - master # branch to trigger on
env:
  duplo_host: https://qa-aws.duplocloud.net
  duplo_token: ${{ secrets.DUPLO_TOKEN }}
  TENANT_NAME: safeb01			# DuploCloud Tenant name

jobs:
  update_service:
    name: Update Service using DuploCtl
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: https://qa-aws.duplocloud.net
      DUPLO_TENANT: safeb01
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions/setup@main

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-service@main
      with:
        service: statefulset
        image: nginx:latest1
        
    - name: Update CronJob 
      uses: duplocloud/actions/update-cronjob@main
      with:
        cronjob: cronjob1
        image: nginx:latest1
         
  deploy:
    # This example get AWS credentials, then lists all S3 buckets.
    name: using GHA Jit update multiple services
    runs-on: ubuntu-latest
    steps:
      - name: aws-jit
        uses: duplocloud/ghactions-aws-jit@master
        with:
         aws_region: us-east-2 #ap-east-1
         duplo_host: ${{ env.DUPLO_HOST }}
         duplo_token: ${{ secrets.DUPLO_TOKEN }}
         tenant: sa0feb1
      - name: AWS us-west-2 - Logintest
        uses: duplocloud/ghactions-aws-jit@master
        with:
          admin: true
          aws_region: us-west-2
      - name: list-vpc
        run: aws ec2 describe-vpcs
      - name: Deploy
        uses: duplocloud/ghactions-service-update@master
        with:
          tenant: "${{ env.TENANT_NAME }}"
          services: |-
            [
              { "Name": "s1", "Image": "nginx:stable1" },
              { "Name": "tag2", "Image": "nginx:stable" }
            ]      

