name: Build and Deploy
on:
  push:
    branches:
      - master # branch to trigger on

jobs:
  update_service:
    name: Update Service
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: https://qa-aws.duplocloud.net
      DUPLO_TENANT: sa0feb1
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions/setup@main

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-service@main
      with:
        service: statefulset
        image: nginx:latest1
