name: Build and Deploy
on:
  push:
    branches:
      - master # branch to trigger on
env:
  duplo_host: https://qa-aws.duplocloud.net
  duplo_token: ${{ secrets.DUPLO_TOKEN }}
  TENANT_NAME: jt-1202-1				# DuploCloud Tenant name
  DUPLO_TENANT_ID: e94226ab-a177-488b-ac72-13d24019bc37	# DuploCloud Tenant Id where lambda is deployed
  LAMBDA_NAME: mylambda	
jobs:
  update_service:
    name: Update Service using DUploCtl
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: ${{ var.DUPLO_HOST }}
      DUPLO_TENANT: sa0feb1
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions/setup@main

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-service@main
      with:
        service: statefulset
        image: nginx:latest1
  deploy:
    # This example get AWS credentials, then lists all S3 buckets.
    name: Deploy with DuploCloud
    runs-on: ubuntu-latest
    steps:
      - name: aws-jit
        uses: duplocloud/ghactions-aws-jit@master
        with:
         aws_region: us-east-2 #ap-east-1
         duplo_host: ${{ var.DUPLO_HOST }}
         duplo_token: ${{ secrets.DUPLO_TOKEN }}
         tenant: "${{ env.DUPLO_TENANT }}"
      - name: AWS us-west-2 - Logintest
        uses: duplocloud/ghactions-aws-jit@master
        with:
          admin: true
          aws_region: us-west-2
      - name: list-vpc
        run: aws ec2 describe-vpcs
      - name: Deploy
        uses: duplocloud/ghactions-service-update@master
        with:
          tenant: "${{ env.TENANT_NAME }}"
          services: |-
            [
              { "Name": "s1", "Image": "nginx:stable1" },
              { "Name": "statefulset", "Image": "nginx:stable" }
            ]
