name: Build and Deploy
on:
  push:
    branches:
      - master # branch to trigger on1
jobs:
  deploy:
    # This example get AWS credentials, then lists all S3 buckets.
    name: Deploy with DuploCloud
    runs-on: ubuntu-latest
    steps:
      - name: aws-jit
        uses: duplocloud/ghactions-aws-jit@master
        with:
          aws_region: ap-east-1
          duplo_host: https://qa-aws.duplocloud.net
          duplo_token: ${{ secrets.DUPLO_TOKEN }}
          tenant: default
      - name: list-s3
        run: aws s3 ls --region ap-east-1
