name: Update Service using update-image
on:
  push:
    branches:
      - master # branch to trigger on

jobs:
  update_service:
    name: Update Service
    runs-on: ubuntu-latest
    environment: 
      name: perf
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: https://perf.duplocloud.net
      DUPLO_TENANT: qa1
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions@vnode24-upgrade

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-image@vnode24-upgrade
      with:
        name: serv3
        image: nginx:123
        type: service

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2     

    - name: Update Multiple Images
      uses: duplocloud/actions/update-images@node24-upgrade
      with:
        services: |
          [
             
            {
              "service": "serv1",
              "image": "nginx:perl"
            },
              {
              "service": "serv2",
              "image": "nginx:perl"
            },
              {
              "service": "serv3",
              "image": "nginx:perl"
            },
               {
              "service": "serv4",
              "image": "nginx:1.27.4"
            },
              {
              "service": "serv5",
              "image": "nginx:1.27.2"
            },
              {
              "service": "serv6",
              "image": "nginx:1.25.4"
            },
                 {
              "service": "serv7",
              "image": "nginx:perl"
            },
              {
              "service": "serv8",
              "image": "nginx:latest"
            },
              {
              "service": "serv9",
              "image": "nginx:alpine"
            },
               {
              "service": "serv10",
              "image": "nginx:perl"
            },
              {
              "service": "serv11",
              "image": "myregistry/frontend:v1.2.4"
            },
              {
              "service": "serv12",
              "image": "myregistry/frontend:v1.2.3"
            },
               {
              "service": "serv13",
              "image": "myregistry/frontend:v1.2.3"
            },
              {
              "service": "serv14",
              "image": "myregistry/frontend:v1.2.3"
            },
                  {
              "service": "serv15",
              "image": "myregistry/frontend:v1.2.3"
            },
              {
              "service": "serv16",
              "image": "myregistry/frontend:v1.2.4"
            },
              {
              "service": "serv17",
              "image": "myregistry/frontend:v1.2.3"
            },
               {
              "service": "serv18",
              "image": "myregistry/frontend:v1.2.3"
            },
              {
              "service": "serv19",
              "image": "myregistry/frontend:v1.2.3"
            },
                 {
              "service": "serv20",
              "image": "myregistry/frontend:v1.2.3"
            }
            
          
          ]

  

        
