name: Update Lambda

on:
  workflow_dispatch:
    inputs:
      lambda:
        description: Lambda name
        required: true
      uri:
        description: A docker image uri or an s3 uri in the form of s3://bucket/path
        required: false

jobs:
  update-lambda:
    runs-on: ubuntu-latest
    environment: qa-aws
    env:
      LAMBDA: ${{ inputs.lambda }}
      URI: ${{ inputs.uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Lambda
        id: duploctl
        shell: bash
        run: |
          if [[ "${URI}" = s3://* ]]; then
            s3_path="${URI#s3://}"
            bucket="${s3_path%%/*}"
            key="${s3_path#*/}"
            duploctl lambda update_s3 "${LAMBDA}" "${bucket}" "${key}"
          else
            duploctl lambda update_image "${LAMBDA}" "${URI}"
          fi
