name: Update Service

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: environment
        default: dev
        required: true
      image:
        description: The full image
        type: string
        required: true

jobs:
  update_service:
    name: Update Service
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: qa-aws.duplocloud.net
      DUPLO_TENANT: 2ee5692a-71cf-4565-a792-0502e13d7a32
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions/setup@v0.0.3

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-service@v0.0.3
      with:
        service: my-service
        image: ${{ inputs.image }}
