name: Build and Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: environment
        default: dev
        required: true
      image:
        description: The full image
        type: string
        required: true
env:
  duplo_host: https://qa-aws.duplocloud.net
  duplo_token: ${{ secrets.DUPLO_TOKEN }}
  TENANT_NAME: jt-1206-1			# DuploCloud Tenant name
jobs:
  deploy:
    # This example get AWS credentials, then lists all S3 buckets.
    name: Deploy with DuploCloud
    runs-on: ubuntu-latest
    steps:
      - name: aws-jit
        uses: duplocloud/ghactions-aws-jit@master
        with:
         aws_region: us-east-2 #ap-east-1
         duplo_host: https://qa-aws.duplocloud.net
         duplo_token: ${{ secrets.DUPLO_TOKEN }}
         tenant: "${{ env.TENANT_NAME }}"
      - name: AWS us-west-2 - Logintest
        uses: duplocloud/ghactions-aws-jit@master
        with:
          admin: true
          aws_region: us-west-2
      - name: list-vpc
        run: aws ec2 describe-vpcs
      - name: Deploy
        uses: duplocloud/ghactions-service-update@master
        with:
          tenant: "${{ env.TENANT_NAME }}"
          services: |-
            [
              { "Name": "serv1", "Image": "nginx:stable" },
              { "Name": "serv2", "Image": "nginx:stable" }
            ]
